[package]
name = "rs_cp"
version = "0.1.0"
edition = "2021"

[dependencies]
copier = {path = "./utils/copier"}
clap = { version = "4.5.23", features = ["derive"] }
env_logger = "0.11.6"
log = "0.4.22"
