[package]
name = "copier"
version.workspace = true
edition.workspace = true

[dependencies]
log.workspace = true
anyhow.workspace = true
libc = "0.2"

[dev-dependencies]
criterion = "0.3"
tempfile = "3.15.0"

[[bench]]
name = "cp_benchmark"
harness = false
